<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="club">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="categories">
          <xs:complexType><xs:sequence><xs:element name="categorie" maxOccurs="unbounded">
            <xs:complexType><xs:attribute name="id" type="xs:ID" use="required"/><xs:attribute name="libelle" type="xs:string" use="required"/></xs:complexType>
          </xs:element></xs:sequence></xs:complexType>
        </xs:element>
        <xs:element name="membres">
          <xs:complexType><xs:sequence><xs:element name="membre" maxOccurs="unbounded">
            <xs:complexType><xs:sequence><xs:element name="nom" type="xs:string"/><xs:element name="prenom" type="xs:string"/><xs:element name="email" type="xs:string"/></xs:sequence>
            <xs:attribute name="id" type="xs:ID"/><xs:attribute name="categorieRef" type="xs:IDREF"/>
          </xs:complexType></xs:element></xs:sequence></xs:complexType>
        </xs:element>
        <xs:element name="concours">
          <xs:complexType><xs:sequence><xs:element name="concours" maxOccurs="unbounded">
            <xs:complexType><xs:sequence><xs:element name="titre" type="xs:string"/><xs:element name="participants">
              <xs:complexType><xs:sequence><xs:element name="participant" maxOccurs="unbounded">
                <xs:complexType><xs:sequence><xs:element name="complexite" type="xs:int"/><xs:element name="tempsExecution" type="xs:int"/></xs:sequence>
                <xs:attribute name="membreRef" type="xs:IDREF"/>
              </xs:complexType></xs:element></xs:sequence></xs:complexType>
            </xs:element></xs:sequence>
            <xs:attribute name="id" type="xs:ID"/><xs:attribute name="categorieRef" type="xs:IDREF"/><xs:attribute name="date" type="xs:date"/><xs:attribute name="coefficient" type="xs:decimal"/>
          </xs:complexType></xs:element></xs:sequence></xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="nom" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>